### ISSUE TITLE
absolute paths in componentlib-source.hpp (0.3.23)

### ISSUE THREAD

**Issue by awgrover** [microflo/microflo#76]
componentlib-source.hpp has #includes with absolute paths, e.g. 
# include "/home/travis/build/microflo/microflo/microflo/core/components/BoolToInt.hpp"

also, componentlib.hpp.
This prevents use in arduino ide after installing the .zip from https://github.com/microflo/microflo/releases/download/0.3.23/microflo-0.3.23.zip)

**Comment by jonnor** [comment]
Confirmed, thanks for reporting!

**Comment by jonnor** [comment]
This now works differently. Since a couple of releases back we no longer create/release an Arduino library. Instead the `microflo generate` command gives a sketch which can be opened and flashed in the IDE directly. See updated documentation at https://github.com/microflo/microflo-example-arduino#microflo-example-arduino
